### ISSUE TITLE
Add Timer::stop

### ISSUE THREAD

**Issue by PvdBerg1998** [stm32-rs/stm32f4xx-hal#106]
Please expose a way to stop a timer. Even better would be a way to init a timer without starting it.
The pause line, located at https://docs.rs/stm32f4xx-hal/0.5.0/src/stm32f4xx_hal/timer.rs.html#210-231 could be extracted if I'm correct. The stm32f1xx hal (originally by japaric) already does this: https://docs.rs/stm32f1xx-hal/0.3.0/src/stm32f1xx_hal/timer.rs.html#149.

**Comment by MarcoIeni** [comment]
I noticed that the `Cancel` trait exists in the [timer](https://docs.rs/crate/embedded-hal/0.2.3/source/src/timer.rs) API. Maybe for this function we should implement it?

**Comment by therealprof** [comment]
@MarcoIeni Sounds like a good idea. Want to give it a shot?

**Comment by MarcoIeni** [comment]
Yes, I will try to work on this :)

**Comment by MarcoIeni** [comment]
A way to stop a timer has been provided by #137 and #148.

> Even better would be a way to init a timer without starting it.

Should we do this? Otherwise we can close this issue.
