### ISSUE TITLE
linking with `rust-lld` failed when stm32f4 crate is 0.8.0

### ISSUE THREAD

**Issue by btrepp** [stm32-rs/stm32f4xx-hal#107]
So I was playing with this crate, and it seems only compatible with stm32f4 0.7.0,
if you have 0.8.0 in the Cargo.toml file, you get the below error

>    Compiling nucleo v0.1.0 (C:\Users\Beau\Code\rust\nucleo)
> error: linking with `rust-lld` failed: exit code: 1
>   |
>   = note: "rust-lld" "-flavor" "gnu" "-L" "C:\\Users\\Beau\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\thumbv7em-none-eabihf\\lib" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\nucleo-eaaf61e3bc003baa.271x5gr5qamfyx15.rcgu.o" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\nucleo-eaaf61e3bc003baa.2rkr7foartczqb4x.rcgu.o" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\nucleo-eaaf61e3bc003baa.2ual8ehbeivzvzip.rcgu.o" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\nucleo-eaaf61e3bc003baa.35u4h8fbwv4k3f1.rcgu.o" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\nucleo-eaaf61e3bc003baa.3giu8u2ftlj6pjgq.rcgu.o" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\nucleo-eaaf61e3bc003baa.3kxoq02mgsdnfnvw.rcgu.o" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\nucleo-eaaf61e3bc003baa.46wer6d7gc7foq85.rcgu.o" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\nucleo-eaaf61e3bc003baa.4pd5vo7t97ol8azi.rcgu.o" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\nucleo-eaaf61e3bc003baa.4vxh1s0pjgr87h8.rcgu.o" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\nucleo-eaaf61e3bc003baa.4yxwb4agdbctcsoq.rcgu.o" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\nucleo-eaaf61e3bc003baa.50bp00c2ip9fgqaq.rcgu.o" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\nucleo-eaaf61e3bc003baa.5361pmkaifxg2t6q.rcgu.o" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\nucleo-eaaf61e3bc003baa.5cc3h2ivztv8wejj.rcgu.o" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\nucleo-eaaf61e3bc003baa.8za6gpd8u0v7785.rcgu.o" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\nucleo-eaaf61e3bc003baa.bb66a0hyld6wge3.rcgu.o" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\nucleo-eaaf61e3bc003baa.nsbs2py5ykaohn2.rcgu.o" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\nucleo-eaaf61e3bc003baa.zqicaw9s06rvxl6.rcgu.o" "-o" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\nucleo-eaaf61e3bc003baa" "--gc-sections" "-L" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps" "-L" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\debug\\deps" "-L" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\build\\nucleo-1088d14277a13585\\out" "-L" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\build\\cortex-m-ed386150c0e5b37b\\out" "-L" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\build\\cortex-m-rt-6e040e191a361a80\\out" "-L" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\build\\cortex-m-semihosting-45af5f14089f505b\\out" "-L" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\build\\stm32f4-9e673fea380aabac\\out" "-L" "C:\\Users\\Beau\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\thumbv7em-none-eabihf\\lib" "-Bstatic" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\libstm32f4xx_hal-cb9b9bd0f92caaa6.rlib" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\libcast-102715931883d16a.rlib" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\libstm32f4-8809c841ede78228.rlib" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\libembedded_hal-6fa59b145b3f24df.rlib" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\libvoid-caccc68030e75381.rlib" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\libnb-8931201fc2df3281.rlib" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\libcortex_m_rt-85ca3f10c3275010.rlib" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\libr0-9e358f45ff0bc31a.rlib" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\libcortex_m-7b43f46696745147.rlib" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\libvolatile_register-e6d630b6a82d3760.rlib" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\libvcell-932c9f4834bcbb12.rlib" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\libbare_metal-6619d71299218a92.rlib" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\libaligned-007dfa6be3bf44e6.rlib" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\libas_slice-f6f01597d8c478e0.rlib" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\libstable_deref_trait-6302bc78b015966f.rlib" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\libgeneric_array-c50a2d94c73ba8d5.rlib" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\libtypenum-b03d23e43a84478c.rlib" "--start-group" "C:\\Users\\Beau\\Code\\rust\\nucleo\\target\\thumbv7em-none-eabihf\\debug\\deps\\libpanic_halt-31b039c857184d9a.rlib" "C:\\Users\\Beau\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\thumbv7em-none-eabihf\\lib\\librustc_std_workspace_core-895383a3232f6572.rlib" "C:\\Users\\Beau\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\thumbv7em-none-eabihf\\lib\\libcore-5594cb4f559bc761.rlib" "--end-group" "C:\\Users\\Beau\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\thumbv7em-none-eabihf\\lib\\libcompiler_builtins-d0c6e5a851d2d415.rlib" "-Tlink.x" "-Bdynamic"
>   = note: rust-lld: error:
>           ERROR(cortex-m-rt): The interrupt vectors are missing.
>           Possible solutions, from most likely to less likely:
>           - Link to a svd2rust generated device crate
>           - Disable the 'device' feature of cortex-m-rt to build a generic application (a dependency
>           may be enabling it)
>           - Supply the interrupt handlers yourself. Check the documentation for details.
> 
> 
> error: aborting due to previous error
> 
> error: Could not compile `nucleo`.
> 
> To learn more, run the command again with --verbose.

**Comment by btrepp** [comment]
I seem to be able to get it to build if I modify it slightly. I will raise a PR

**Comment by aurelj** [comment]
Fixed by the merged PR #108
