### ISSUE TITLE
proposed example: countdown timer (GPIO, ADC, timers, IRQs, I2C/OLED)

### ISSUE THREAD

**Issue by nebelgrau77** [stm32-rs/stm32f4xx-hal#129]
As I finally managed to put together a working (yet seriously improvable) "quiet timer", it could be useful as an example of various features of the F4xx-hal crate. It has I2C-connected OLED display, ADC, timers and interrupts. It does have some issues: the board has to be reset after powering up to get the display to run (something related to the display driver), and the ADC reading needs to be more stable, but it does show some things that could be useful to others. 

https://github.com/nebelgrau77/STM32F4-OLED-IRQ_timecounter

**Comment by therealprof** [comment]
Nice, thanks for letting us know.
