### ISSUE TITLE
No implementation of `embedded_hal::blocking::serial::Write` for `stm32f4xx::serial::Tx`

### ISSUE THREAD

**Issue by mitchmindtree** [stm32-rs/stm32f4xx-hal#184]
I just noticed that there is no implementation of the [`embedded_hal::blocking::serial::Write` trait](https://docs.rs/embedded-hal/0.2.4/embedded_hal/blocking/serial/trait.Write.html) when porting an application from my teensy4.0 to the stm32f407. Is there any reason for omitting this? If not, would you be happy to accept an implementation?

If so, would it be acceptable to implement it in terms of the existing `embedded_hal::serial::Write` implementation? I'm imagining something like this (unchecked):

```rust
impl<T> embedded_hal::blocking::serial::Write<u8> for serial::Tx<T>
where
    serial::Tx<T>: embedded_hal::serial::Write<u8>,
{
    type Error = serial::Error;
    fn bwrite_all(&mut self, bytes: &[u8]) -> Result<(), Self::Error> {
        for &b in bytes {
            loop {
                match self.write(b) {
                    Err(nb::Error::WouldBlock) => continue,
                    Err(err) => return Err(err),
                    Ok(()) => break,
                }
            }
        }
        Ok(())
    }

    fn bflush(&mut self) -> Result<(), Self::Error> {
        self.flush()
    }
}
```

**Comment by therealprof** [comment]
Hi @mitchmindtree. You're totally right that this is just an oversight and yes, we'd  be happy to accept a PR to rectify this. 🎉
