### ISSUE TITLE
Enable voltage overdrive for HCLK > 168 MHz?

### ISSUE THREAD

**Issue by birkenfeld** [stm32-rs/stm32f4xx-hal#196]
The reference manual RM0090 states that for HCLK > 168 MHz on F42x and F43x, the over-drive mode should be enabled (the procedure is on page 123). I have run some devices at 180 MHz without over-drive and not seen problems, but would it be more proper to do this in `RCC.freeze()` if indicated?

**Comment by thalesfragoso** [comment]
You are right, we should do this. Thanks for spotting it.

**Comment by therealprof** [comment]
Indeed, I agree. Thanks for spotting this. Are you going to work on a PR @birkenfeld?

**Comment by birkenfeld** [comment]
Sure, I'm on it.
