### ISSUE TITLE
ADC initialization may panic

### ISSUE THREAD

**Issue by ryan-summers** [stm32-rs/stm32f4xx-hal#205]
When constructing ADC3, I observed the initialization function panic. Upon debugging, it appears that the initializer is panicking during `adc::calibrate()` because `vref_samp` is set to zero.

Upon inspection of the STM32F4xx reference manual, I found this snippet:
![image](https://user-images.githubusercontent.com/8771450/90748580-a5bf2b00-e2d2-11ea-8d59-765fae713db2.png)

It does not appear that it is valid to read the VREF_INT signal from any ADC other than ADC1.

**Comment by therealprof** [comment]
Makes sense.

**Comment by ryan-summers** [comment]
The result is that we don't have a calibrated VDDA for ADC2 and ADC3. Possible solutions:
* Allow user to manually specify VREF+ in the constructor
* Provide a function explicitly to acquire VREF+ calibration from the ADC1 peripheral and take that as a constructor argument for the other ADCs
