### ISSUE TITLE
TIM DMA transfer support

### ISSUE THREAD

**Issue by DimaaIO** [stm32-rs/stm32f4xx-hal#227]
Hi,
I'm trying to implement the Dshot protocol, similar to the one WS2812B uses.
This is the code where I already fail:
```rust
let dma1_streams = dma::StreamsTuple::new(device.DMA1);
let dma_transfer = dma::Transfer::init(
    dma1_streams.4,
    device.TIM3.ccr1,
    cortex_m::singleton!(: [u16; 18] = [0; 18]).unwrap(),
    None,
    dma::config::DmaConfig::default()
        .fifo_enable(true)
        .memory_increment(true),
);
```
Unfortunately it doesn't let me compile and returns an error message:
```
the trait bound `stm32f4::generic::Reg<u32, stm32f4xx_hal::stm32::tim3::_CCR>: stm32f4xx_hal::dma::traits::PeriAddress` is not satisfied
the trait `stm32f4xx_hal::dma::traits::PeriAddress` is not implemented for `stm32f4::generic::Reg<u32, stm32f4xx_hal::stm32::tim3::_CCR>`
```
I've seen in the source code that it requires the struct `CCR1<pac::TIM3>` to use `TIM3_CH1`, but where do I get it from?

**Comment by thalesfragoso** [comment]
Sorry, this should be better documented, you can find them here:
https://github.com/stm32-rs/stm32f4xx-hal/blob/385cb9707994d41a6199d1d139b49cfa4490a87d/src/dma/traits.rs#L315

Unfortunately, it seems that we forgot to add a way to create these types from outside the crate .-.

Changing this:
https://github.com/stm32-rs/stm32f4xx-hal/blob/385cb9707994d41a6199d1d139b49cfa4490a87d/src/dma/traits.rs#L288
to `pub struct $name<T> (pub T);` should be a decent solution, but I will think for a bit to see if it's the best one.
