### ISSUE TITLE
Spurious I2C bus errors occur

### ISSUE THREAD

**Issue by ryan-summers** [stm32-rs/stm32f4xx-hal#274]
Due to errata in the STM32F4 I2C implementation, the I2C module may spuriously (and erroneously) indicate bus errors.

![image](https://user-images.githubusercontent.com/8771450/111497825-b6892f80-8741-11eb-8322-1ea92acaf61b.png)

We should likely just throw out the BERR bit status instead of indicating incorrect errors, as advised by the errata.

The erratum is found in the following Errata sheets
Reference:
* [F42xx Errata](https://www.st.com/resource/en/errata_sheet/dm00068628-stm32f427437-and-stm32f429439-line-limitations-stmicroelectronics.pdf)
* [F40xx/F41xx Errata](https://www.st.com/resource/en/errata_sheet/dm00037591-stm32f405407xx-and-stm32f415417xx-device-limitations-stmicroelectronics.pdf)
* [STM32F46x/STM32F47x Errata](https://www.st.com/resource/en/errata_sheet/dm00220774-stm32f469xx-and-stm32f479xx-device-errata-stmicroelectronics.pdf)
* [F44x Errata](https://www.st.com/resource/en/errata_sheet/dm00155929-stm32f446xcxe-device-limitations-stmicroelectronics.pdf)

**Comment by therealprof** [comment]
I haven't seen that behaviour in real life but it certainly makes sense to implement the suggested workarounds for the less lucky amongst us. 😅

**Comment by ryan-summers** [comment]
We have been observing them spuriously on devices approximately once per day or so. The error is quite rare, but when you have a lot of bus transfers and have long running devices, it definitely props its head up. I'll add a fix for this soon.
