### ISSUE TITLE
How can `static mut` variables not require unsafe access? 

### ISSUE THREAD

**Issue by Maldus512** [stm32-rs/stm32f4xx-hal#307]
I was working on an interrupt handler and I noticed that some of the examples (e.g. https://github.com/stm32-rs/stm32f4xx-hal/blob/bb160bbe8604bccf28557975131d0afdb2fa1014/examples/blinky-timer-irq.rs#L45) use `static mut` variables in an interrupt context and successfully compile **without** using unsafe blocks. 
How does this work? By trying out stuff I noticed that the compilation seems to fail (as I would expect, without unsafe blocks) if the not all `static mut` are declared at the beginning of the function. Does this have something to do with the `#[interrupt]` macro?

**Comment by therealprof** [comment]
Yes, the `#[interrupt]` macro transforms the `static mut` and provides a safe abstraction. cf. https://github.com/rust-embedded/cortex-m-rt/blob/master/macros/src/lib.rs
