### ISSUE TITLE
CountDown timer API should be configured with a time period, not a frequency

### ISSUE THREAD

**Issue by dzimmanck** [stm32-rs/stm32f4xx-hal#378]
The builder methods (start and start_countdown) accept a variable called timeout, which must be convertible into Hertz.  This does not make sense to me.  A Countdown should "count down from X" where X is a time duration, not a frequency.  This leads to non-sensical looking code like:

`let frequency = timeout.into.0`

Also, it means you loose A LOT of precision on the timer.  You can no longer precisely control the timer delay in increments of cycles due to this division.

`let ticks = self.clk.0 / frequency;`

**Comment by burrbull** [comment]
Related to https://github.com/rust-embedded/embedded-hal/issues/201

**Comment by dbrgn** [comment]
Related to #235.

**Comment by burrbull** [comment]
#381
