### ISSUE TITLE
Why is PinState no longer used from embedded-hal in 0.11?

### ISSUE THREAD

**Issue by birkenfeld** [stm32-rs/stm32f4xx-hal#414]
This seems like a regression; the two types look identical.

**Comment by burrbull** [comment]
It was preparing for #388. Is it breaking?

**Comment by birkenfeld** [comment]
It breaks when updating, but that's ok. The reason I was wondering is that it seemed strange that common definitions from `hal` were repeated in this crate.

**Comment by birkenfeld** [comment]
Great, thanks!
