### ISSUE TITLE
Typo in variable name? (khz and mhz)

### ISSUE THREAD

**Issue by jdhoek** [stm32-rs/stm32f4xx-hal#433]
I was looking at the [source](https://github.com/stm32-rs/stm32f4xx-hal/blob/8fa1bef653f292f7bd131dbef5ae300cd2c04cf5/src/time.rs#L61) of `time.rs` and noticed this:

```rust
impl From<KiloHertz> for Hertz {
    fn from(mhz: KiloHertz) -> Self {
        Self(mhz.0 * 1_000)
    }
}
```

Am I right in assuming that `mhz` could be changed into `khz` here for readability sake?

**Comment by burrbull** [comment]
I'm planning to remove this anyway. See #430
