### ISSUE TITLE
`From` traits for GPIO pin types

### ISSUE THREAD

**Issue by romancardenas** [stm32-rs/stm32f4xx-hal#506]
Hi! I am wondering why this library does not implement the `From` trait for `Pin`, `PartiallyErasedPin`, and `ErasedPin`.
Something like this:
```rust
impl<const P: char, const N: u8, MODE> From<Pin<P, N, MODE>> for ErasedPin<MODE> {
    fn from(p: Pin<P, N, MODE>) -> Self {
            p.erase()
    }
}
```
I'm pretty new into embedded Rust development, so sorry if this is a silly question.
Thanks in advance!

**Comment by burrbull** [comment]
Good point.
Please, make PR.

**Comment by romancardenas** [comment]
I opened a the pull request #507 with this.
