### ISSUE TITLE
STM32F413 UART4 missing impls

### ISSUE THREAD

**Issue by fbstj** [stm32-rs/stm32f4xx-hal#548]
I'm playing around trying rust embedded for the first time using an existing board-stack with an F413 I have which has the UART4 for "debugging" but it seems the formatting infrastructure for this particular choice is commented out without explanation?

https://github.com/stm32-rs/stm32f4xx-hal/blob/master/src/serial.rs#L869

**Comment by fbstj** [comment]
I think this might be because of stm32-rs/stm32-rs#413 which may be being fixed by stm32-rs/stm32-rs#754

**Comment by burrbull** [comment]
Waiting for new `stm32f4` crate release https://github.com/stm32-rs/stm32f4xx-hal/pull/533
