### ISSUE TITLE
Issue with creating new instance of can for STM32F429 Discovery board

### ISSUE THREAD

**Issue by ApoorvSingh0009** [stm32-rs/stm32f4xx-hal#558]
Problem while executing the example file can-send.rs for stm32f429 , cannot find any way to instantiate can using new(), the compiler shows error saying there is no such function like new().
I have been facing this issue since a while. It would be great if you could help. 

![image](https://user-images.githubusercontent.com/34118020/207008114-872b433c-c61d-4cf4-bf7c-47aaa077e7cb.png)

**Comment by burrbull** [comment]
have you enabled `can` feature?

**Comment by ApoorvSingh0009** [comment]
> have you enabled `can` feature? `--features stm32f429,can`

Will try it now.

**Comment by burrbull** [comment]
Here
```
[dependencies.stm32f4xx-hal]
version = "0.13.2"
features = ["stm32f429", "rt", "can"] 
```

**Comment by burrbull** [comment]
you've missed `dp.CAN1, `

**Comment by burrbull** [comment]
Its because `stm32f4xx-hal` depends on old `bxcan`.
Try to use `stm32f4xx-hal` from git or use `bxcan` 0.6

**Comment by ApoorvSingh0009** [comment]
> Its because `stm32f4xx-hal` depends on old `bxcan`. Try to use `stm32f4xx-hal` from git or use `bxcan` 0.6

Exactly, I did the same and it compiles perfectly but I am yet to test on hardware. 
Thanks a lot. @burrbull
