### ISSUE TITLE
USB fails without any errors on nightly

### ISSUE THREAD

**Issue by t348575** [stm32-rs/stm32f4xx-hal#574]
USB appears to fail when the `UsbDeviceBuilder` is called, regardless of what it is used for (serial, hid etc). The device gets stuck at this line and never goes over (does not panic, just gets stuck). Not sure if this is an issue with `stm32f4xx-hal` or with [usb-device](https://github.com/rust-embedded-community/usb-device), and it is happening only on nightly, all usb forms run fine on stable. 

## Environment:
* stm32f401ccu6 (black pill)
* nighly version (failing): 1.69.0
* stable version (working): 1.67.0

**Comment by burrbull** [comment]
It could also be related to https://github.com/stm32-rs/synopsys-usb-otg/issues/33

Try `cargo update`, please.

**Comment by t348575** [comment]
@burrbull Yep that worked.
