### ISSUE TITLE
SPI1 MISO pin alternate mode always low.

### ISSUE THREAD

**Issue by Leonana69** [stm32-rs/stm32f4xx-hal#589]
If I config the SPI pins as alternate mode, the MISO pin (PA6) will always be low, and I can not read anything from the sensor. But in the c version HAL library, all three pins are configured the same and it works fine.
```
let spi1_pins = (
    gpioa.pa5.into_alternate::<5>().speed(Speed::VeryHigh),
    // gpioa.pa6.into_alternate::<5>().speed(Speed::VeryHigh), // this not work
    gpioa.pa6, // this works
    gpioa.pa7.into_alternate::<5>().speed(Speed::VeryHigh),
);
let mode = spi::Mode {
    polarity: spi::Polarity::IdleLow,
    phase: spi::Phase::CaptureOnFirstTransition,
};

let mut spi1 = dp.SPI1.spi(spi1_pins, mode, 1.MHz(), &clocks);
```

I found that the PUPDR is not configured in the Pin::Mode function as the c version does. The problem may be caused by this.

**Comment by burrbull** [comment]
try to add [.internal_resistor(Pull::WhatYouNeed)](https://docs.rs/stm32f4xx-hal/latest/stm32f4xx_hal/gpio/struct.Pin.html#method.internal_resistor)

**Comment by Leonana69** [comment]
> try to add [.internal_resistor(Pull::WhatYouNeed)](https://docs.rs/stm32f4xx-hal/latest/stm32f4xx_hal/gpio/struct.Pin.html#method.internal_resistor)

This works, thank you! Also, maybe update the example (the analog-stopwatch-with-spi-ssd1306.rs does not explicitly set the internel_pull)?
