### ISSUE TITLE
[Done] How to read data from SPI Slave?

### ISSUE THREAD

**Issue by eZioPan** [stm32-rs/stm32f4xx-hal#591]
UPDATE:

for anyone arrived here: SPI Slave mode only implement in DMA mode for now, any contribution is appreciated.

---

I try to make a demo project that send data from `SPI1` to `SPI2`, thus I config `SPI1` in `Master` mode using `dp.SPI1.spi()`, and `SPI2` in `Slave` mode use `dp.SPI2.spi_slave()`.

There are `.send()` and `.read()` methods on `SPI1` (which is in `Master` mode), but I cannot find `.read()` on `SPI2` (which is in `Slave` mode).

How can I read data from `SPI2`? Is there something I missing?

Thanks!

**Comment by vv-ab** [comment]
Same problem here. Does somebody have a SPI slave example?

**Comment by Maytastico** [comment]
I tried this too and  failed. pls help :(
I would appreciate an example as well.
Thanks!

**Comment by burrbull** [comment]
There is no example because it is not implemented yet. Slave mode should work only with DMA for now.

Any contribution is appreciated.

**Comment by eZioPan** [comment]
@burrbull thanks, should I left this issue open for tracing purpose, or just close it?

**Comment by burrbull** [comment]
leave open

**Comment by kKdH** [comment]
> There is no example because it is not implemented yet. Slave mode should work only with DMA for now.

@burrbull, thank you for clarification.

**Comment by burrbull** [comment]
I've tried to make draft https://github.com/stm32-rs/stm32f4xx-hal/pull/609 but I can't test it.

**Comment by eZioPan** [comment]
> I've tried to make draft #609 but I can't test it.

@burrbull thanks for working on this! I have try new code on my STM32F411RET6, and I might find some bugs. I change some code to let it works on my chip. Would you spare some time to review my suggestion? thanks again.
