### ISSUE TITLE
`SpiSlaveX` type should map to a `SpiSlave` in `spi!` macro

### ISSUE THREAD

**Issue by eZioPan** [stm32-rs/stm32f4xx-hal#634]
@burrbull

in line
[spi.rs line 170 spi! macro](https://github.com/stm32-rs/stm32f4xx-hal/blob/5b66aa4fc890c60f726c1446e5d5647c3cfbf5d4/src/spi.rs#LL170C83)

```rust
pub type $SpiSlave<const BIDI: bool = false, W = u8> = Spi<$SPI, BIDI, W>;
```

`$SpiSlave` should map to `SpiSlave` struct rather than `Spi` struct.

**Comment by burrbull** [comment]
Please, make PR

**Comment by eZioPan** [comment]
@burrbull please reviewing my PR
