### ISSUE TITLE
Assembly instructions take longer then expected. stm32f401

### ISSUE THREAD

**Issue by dvdsk** [stm32-rs/stm32f4xx-hal#643]
### Context
For one of my hobby projects own usb project (reading/spying? usb as a third party). It uses an stm32f401 (black pill board). But now I am starting to doubt myself. I have set the mcu to run at 84 Mhz, Usb full speed runs at 12 so that should give me 7 clock cycles for each usb bit. I wrote an interrupt routine in armv7 assembly that aquires a bunch of samples (loop unrolled). I padded each gpio read  (load instruction) with nop's such that the period between samples is 7 clock cycles. I also made sure the interrupt is running from .data (so it is kept in RAM instead of flash). 

This didn't really seem to work. Yesterdays I got the idea to put a pin high at the start of the interrupt (and low at the end) to time the whole routine. The timing was way off, a factor 5. This gave me the idea that something might be wrong with the clock. 

### Issue
So I made an interrupt routine in assembly which pulls a gpio high then goes through 100 nops before putting the gpio low.  
 - at 84 Mhz a NOP should take one clock cycle or ~= 12 ns
-  100 NOPS should take 1.2 micro seconds.

I monitor the GPIO using a cheap 24Mhz logic analyzer. It measures a period of 6.3 micro seconds. In the screenshot below you see the results, on D6 the debug pulse of 100 nops.
![20230519_20h51m36s_grim](https://github.com/stm32-rs/stm32f4xx-hal/assets/11743287/e4a96b3f-742d-4f64-8fdf-635fb55eb054)

Edit [2023-05-23]: **I made a mistake using the PAC, which caused MCO1 to be set to HSI (16 Mhz). Today I discovered the PLL runs at the expected freq. Nothing seems to be wrong there.**
I also used MCO1 to output the pll with a div of 5. That should output a lock signal of about 17 Mhz. Since the logic analyzer can only sample to 24 Mhz I would expect to read 24 or 17 Mhz. Instead it finds 3 (see screenshot below D7).
![20230519_21h11m05s_grim](https://github.com/stm32-rs/stm32f4xx-hal/assets/11743287/d991dc94-5fc1-4ca9-80a0-ed88d4a71458)

### Clock Settings tried
The clock was set using: 
```rust
    let mut dp = Peripherals::take().unwrap();
    let rcc = dp.RCC.constrain();
    let clocks = rcc
        .cfgr
        .sysclk(84.MHz())
        .freeze();
```
I also printed all registers leading to the system clock and compared them to the Reference manual (RM0368) clock diagram. These where:

```
INFO  plln: 10101000
└─ decodes to 168
INFO  pllp 1
└─ decodes to 4
INFO  pllm 1000
└─ decodes to 8
INFO  pllq 111
└─ decodes to 7
INFO  pllsrc is hse false
INFO  PLL on: true
INFO  system clock is pll: true
INFO  AHB prescaler hclock 0
└─ decodes system clock not devided
```

I also tried:
```rust
rcc.cfgr.use_hse(25.MHz()).sysclk(84.MHz()).freeze()
```
and _hse_ speeds of 16 and 8 MHz. In those cases the board became unresponsive.

### Source
I put up a minimal example at: https://github.com/evavh/break-enforcer/blob/clock_issues/src/main.rs
The assembly thats run is in: https://github.com/evavh/break-enforcer/blob/clock_issues/src/test_interrupt.rs

### Possible user error
Edit [2023-05-23]: **I made a mistake using the PAC, which caused MCO1 to be set to HSI (16 Mhz). Today I discovered the PLL runs at the expected freq. Nothing is wrong with the clock.**
I also had a look at the HSE clock. It should have a freq of 25 Mhz (listed on the black pill bord page and can be read on the crystal). If I output it with a divider of 4 I would expect to read something close to 6.25 instead I measure 4 Mhz, implying the crystal is running at 16Mhz. Configuring as such leads to an unresponsive board. This implies my understanding or measurements are wrong. The logic analyzer works fine for 12MHz usb full speed packets which implies it is not at fault here.

**Comment by burrbull** [comment]
`rcc.cfgr.use_hse(25.MHz()).sysclk(84.MHz()).freeze()`

**Comment by dvdsk** [comment]
> `rcc.cfgr.use_hse(25.MHz()).sysclk(84.MHz()).freeze()`

Unfortunately that (and `use_hse(16.MHz())`) does not work. I have updated the issue/question to reflect me trying that.

**Comment by dvdsk** [comment]
Update: today I got MCO pll out working in C via stm32cube. With the firmware setup to run at 84Mhz. The PLL is now significantly higher

**Comment by dvdsk** [comment]
At this point I could use some guidance on how to find what specifically is going wrong on the Rust side. Is there anyone who could mentor me in figuring this out? I suspect something might be going wrong in stm32fxx-hal when configuring the clock, no idea how to confirm that though.

**Comment by dvdsk** [comment]
Update: today I found out I made a mistake configuring MCO1. The clockspeed is set correctly by stm32f4xx-hal. I will leave this issue open while I continue to look into why the interrupt of NOPS takes longer then expected.

**Comment by dvdsk** [comment]
>         (*hal::pac::RCC::ptr()).cfgr.write(|w| {
>             w.mco1().pll();
>             w.mco1pre().div5()
>         });

Configuring the MCO like this overwrites some clock configuration. As `write` resets fields to their default value. It looks like me misconfiguring the MCO was the cause of all my troubles here. Ill double check with my original code base and then close the issue.

**Comment by dvdsk** [comment]
> @dvdsk Did you get it working correctly using
> 
> ```rust
> cfgr.modify|_,w| {
>     w.mco1().pll();
>     w.mco1pre().div5()
> });
> ```
> 
> instead? or something similar?

yes, that gave me correct mco output
