### ISSUE TITLE
SDIO support for stm32f446

### ISSUE THREAD

**Issue by atoktoto** [stm32-rs/stm32f4xx-hal#711]
Seems like the feature was disabled some time back:
https://github.com/stm32-rs/stm32f4xx-hal/blame/0ffa14c6deb10e0f25d3300aa2b1f03baaa8b047/Cargo.toml#L225

Is there a reason for that and/or a chance that it will be supported?

**Comment by burrbull** [comment]
Try to uncomment and test.
If it works fine, we'll enable it.

**Comment by burrbull** [comment]
Should work now.
