### ISSUE TITLE
External interrupt source not correct

### ISSUE THREAD

**Issue by kitzin** [stm32-rs/stm32f4xx-hal#77]
Relevant code and relevant datasheet section from `STM32F411RE` MCU.
https://github.com/stm32-rs/stm32f4xx-hal/blob/216f7f62e2b7d035b10a9e060a10de44faff6ce5/src/gpio.rs#L190-L217
https://github.com/stm32-rs/stm32f4xx-hal/blob/216f7f62e2b7d035b10a9e060a10de44faff6ce5/src/gpio.rs#L89-L92
https://github.com/stm32-rs/stm32f4xx-hal/blob/216f7f62e2b7d035b10a9e060a10de44faff6ce5/src/gpio.rs#L713-L730
![asdf](https://i.imgur.com/eNKSIt1.png)

So for example if I would to be pin `PB2` the interrupt line it should select is `EXTI2`.

```
$extigpionr = 1
$i = 1
```
which would imply
```
offset = 4
self.i = 1
```
in `make_interrupt_source`

This writes `0bXXXX_XXXX_0001_XXXX` to the `SYSCFG_EXTICR1` register. This enables `EXTI1` which is not the correct one for `PB2` pin.

Not completely sure if I missed something, or the implementation is not correct?

Thanks!

**Comment by aurelj** [comment]
Indeed, the implementation looks wrong.
offset should be:
`let offset = 4 * (self.i % 4);`

A fix is on its way.

**Comment by aurelj** [comment]
Should be fixed now.
Oh, and thanks for the detailed bug report !
