### ISSUE TITLE
About interrupts in the SPI DMA example.

### ISSUE THREAD

**Issue by oh-wind** [stm32-rs/stm32f4xx-hal#812]
I am a beginner in embedded systems. Why is DMA2_STREAM4 interrupt used in the [spi-dma](https://github.com/stm32-rs/stm32f4xx-hal/blob/704aa0920df9c189325f4453dbd354152bf4a28d/examples/spi-dma.rs#L87C64-L87C76) example? I don't quite understand, is this a mistake?

**Comment by burrbull** [comment]
You are right there should be DMA1_STREAM4. Maybe some copy-paste mistake.

Could you open an fix PR?

**Comment by oh-wind** [comment]
I'd love to do this！
